### ISSUE TITLE
ログイン機能を実装する

### ISSUE THREAD

**Issue by abgata20000** [ichika4561/Sports#5]
### 経緯・目的 
ログイン機能を実装してログインしていないとできない操作とログインしていなくてもできる操作を管理できるようにする

### 概要・提案 
facebookログインを実装途中みたいだったのでそのまま利用するといいと思います。
[![Screenshot from Gyazo](https://gyazo.com/eccb05da7a203ea52516b7bba1da4d8c/raw)](https://gyazo.com/eccb05da7a203ea52516b7bba1da4d8c)

ログインボタンはヘッダーメニューの右端にあるのが一般的な気がします。

### 解決の定義 
- [x] ログインボタンが表示されるようになること
- [x] ログインができるようになること
- [x] ログイン中はユーザー名とログアウトボタンが表示されるようになること
- [x] ログアウトができるようになること

**Comment by ichika4561** [comment]
```
https://github.com/ichika4561/Sports/commit/b1aca78ace6f095fa4f9aaebd3fe69f02bf61afb
```
にて完了しました！
プルリク出来なかったので、URLで失礼します。
ただ、ユーザー名の位置がやや上で修正が必要ですが、
どのようにしたら良いのか不明なのと、優先順位低めなので、置いときました。

**Comment by abgata20000** [comment]
@ichika4561 
作業完了したらissueは閉じましょう
