### ISSUE TITLE
機能を実現するために必要なスキーマ設計をする

### ISSUE THREAD

**Issue by abgata20000** [ichika4561/Sports#7]
### 経緯・目的 
> サイト全体機能
検索機能（スポーツのジャンル、開催日時、開催場所）

>投稿内容
タイトル
ジャンル
開催日時
開催エリア
その他
随時変更

上記の機能を実現するために必要なスキーマを考える

### 概要・提案 
- ジャンルや開催場所やエリアの内容が固定でいいのであれば、
https://github.com/makandra/active_type 
とか使うと便利だと思う

- 開催日時は、開始と終了両方管理できるようにしたほうが使いやすいと思う
- 下書きとか公開とかのステータスを管理できるようにしておくと便利だと思う 
- 参加人数とかもあるといいかも

### 解決の定義 
- [x] 必要な情報を管理できるテーブルが作成されるようになること
- [x] モデルごとのリレーションが適切に設定されること

**Comment by ichika4561** [comment]
お疲れ様ですー！

```
* ジャンルや開催場所やエリアの内容が固定でいいのであれば、
  https://github.com/makandra/active_type
  とか使うと便利だと思う
```
公式ドキュメントでは理解ができず、
active_typeで調べたもののよくわかりませんでした。
どう使うのか、何ができるのかわかる記事ってありますか？

**Comment by abgata20000** [comment]
@ichika4561 間違えました。
https://github.com/zilkey/active_hash
こっちでした。
テーブルを持たずにActiveRecordと同じようにデータを管理するのに便利です
refs: https://qiita.com/ryoff/items/88670edb3a656ca69d7b


 https://github.com/makandra/active_type は、
機能に特化したモデルを作成する際に便利なライブラリです
